# generated by datamodel-codegen:
#   filename:  s.json
#   timestamp: 2021-07-09T16:12:18+00:00

from __future__ import annotations

from pydantic import BaseModel


class Model(BaseModel):
    token: str
    team_id: str
    team_domain: str
    channel_id: str
    channel_name: str
    user_id: str
    user_name: str
    command: str
    text: str
    api_app_id: str
    is_enterprise_install: str
    response_url: str
    trigger_id: str
